# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install Dependencies
      run: npm install
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_VUE_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        envkey_VUE_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        envkey_VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        envkey_VUE_APP_FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        envkey_VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        envkey_VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        envkey_VUE_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        envkey_VUE_APP_NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
        envkey_VUE_APP_RSS_PARSING_FUNCTION_URL: ${{ secrets.RSS_PARSING_FUNCTION_URL }}
        file_name: .env
    - name: Check env file contents
      run: cat .env
    - name: Build
      run: npm run build
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
